name: Gradle Check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Check spotless
        run: ./gradlew spotlessCheck

  check-simulation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Automated sim test
        run: ./gradlew simulateJavaDebug -PautomatedTest=true
